### ISSUE TITLE
Supported version information is outdated. Please update.

### ISSUE THREAD

**Issue by ytama** [ibm-cloud-docs/vsrx#10]
Hello,
Could you please update this page?
https://cloud.ibm.com/docs/vsrx?topic=vsrx-vsrx-versions
15.1 is still on the table, but this version is already EOS by Juniper.
And 20.4R3-S2 is not on the table, but is already available on IBM Cloud.
Thanks!

**Comment by jbmitch** [comment]
Hello @ytama . Per Andrew Sloma:

"We leave all versions in the table even though it's EOS
. There is a blurb at the bottom pointing them to support dates, but we have customers running on all these, so we don't remove them.
 We removed 20.4R3-S2 intentionally, since it has a bad bug."
