### ISSUE TITLE
https://cloud.ibm.com/docs/infrastructure/vsrx?topic=vsrx-creating-the-new-interface-zone-and-address-book-subnet&locale=en-us

### ISSUE THREAD

**Issue by chechuironman** [ibm-cloud-docs/vsrx#4]
the example is just for HA
If I try to do the same but using ge-0/0/0.1 it doesnt work

`[edit security zones security-zone CUSTOMER-PRIVATE]
  'interfaces ge-0/0/0.1'
    Interface ge-0/0/0.1 must be configured under interfaces
error: configuration check-out failed`

**Comment by jbmitch** [comment]
Fixed
